id = "lammps"
name = "LAMMPS"
version = "0.1.0"
schema_version = 1
authors = ["hanxu <eisult@foxmail.com>"]
description = "LAMMPS molecular dynamics input script (.in) syntax highlighting for Zed"
repository = "https://github.com/ECHOUniverse/LAMMPS-Zed"
languages = ["languages/lammps"]
snippets = ["./snippets/lammps.json"]

[grammars.lammps]
repository = "https://github.com/ECHOUniverse/tree-sitter-lammps"
rev = "b91533162dd35827315a03150be753886983250e"
