use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=data/");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("command_database.rs");
    let data_dir = Path::new("data");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n");
    code.push_str("use crate::commands::schema::*;\n");
    code.push_str("use once_cell::sync::Lazy;\n\n");
    code.push_str("pub static COMMAND_DB: Lazy<CommandDatabase> = Lazy::new(|| {\n");
    code.push_str("    CommandDatabase {\n");

    // Generate general_commands from commands.toml
    generate_commands(&data_dir, &mut code);

    // Generate style categories from their respective TOML files
    let style_files: &[(&str, &str, &str)] = &[
        ("pair_styles", "pair_styles.toml", "StyleCategory::Pair"),
        ("fix_styles", "fixes.toml", "StyleCategory::Fix"),
        ("compute_styles", "computes.toml", "StyleCategory::Compute"),
        ("bond_styles", "bond_styles.toml", "StyleCategory::Bond"),
        ("angle_styles", "angle_styles.toml", "StyleCategory::Angle"),
        ("dihedral_styles", "dihedral_styles.toml", "StyleCategory::Dihedral"),
        ("improper_styles", "improper_styles.toml", "StyleCategory::Improper"),
        ("kspace_styles", "kspace_styles.toml", "StyleCategory::KSpace"),
    ];

    for &(field_name, file_name, category) in style_files {
        generate_styles(&data_dir, field_name, file_name, category, &mut code);
    }

    code.push_str("    }\n");
    code.push_str("});\n");

    fs::write(&dest_path, code).unwrap();
}

fn generate_commands(data_dir: &Path, code: &mut String) {
    let path = data_dir.join("commands.toml");
    let content = match fs::read_to_string(&path) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("cargo:warning=Failed to read {:?}: {}", path, e);
            code.push_str("        general_commands: vec![],\n");
            return;
        }
    };

    let value: toml::Value = match content.parse() {
        Ok(v) => v,
        Err(e) => {
            eprintln!("cargo:warning=Failed to parse {:?}: {}", path, e);
            code.push_str("        general_commands: vec![],\n");
            return;
        }
    };

    code.push_str("        general_commands: vec![\n");

    if let Some(commands) = value.get("commands").and_then(|c| c.as_array()) {
        for cmd in commands {
            let name = str_val(cmd, "name");
            let category = str_val(cmd, "category");
            let doc_short = str_val(cmd, "doc_short");
            let doc_full = str_val(cmd, "doc_full");
            let cat_enum = map_command_category(&category);
            let params_code = generate_parameters(cmd);

            code.push_str(&format!(
                "            CommandDef {{\n\
                                name: {:?}.to_string(),\n\
                                category: {},\n\
                                parameters: vec![{}],\n\
                                doc_short: {:?}.to_string(),\n\
                                doc_full: {:?}.to_string(),\n\
                                lammps_version: None,\n\
                            }},\n",
                name, cat_enum, params_code, doc_short, doc_full
            ));
        }
    }

    code.push_str("        ],\n");
}

fn generate_styles(
    data_dir: &Path,
    field_name: &str,
    file_name: &str,
    category: &str,
    code: &mut String,
) {
    let path = data_dir.join(file_name);
    let content = match fs::read_to_string(&path) {
        Ok(c) => c,
        Err(_) => {
            code.push_str(&format!("        {}: vec![],\n", field_name));
            return;
        }
    };

    let value: toml::Value = match content.parse() {
        Ok(v) => v,
        Err(e) => {
            eprintln!("cargo:warning=Failed to parse {:?}: {}", path, e);
            code.push_str(&format!("        {}: vec![],\n", field_name));
            return;
        }
    };

    code.push_str(&format!("        {}: vec![\n", field_name));

    if let Some(styles) = value.get("styles").and_then(|s| s.as_array()) {
        for style in styles {
            let name = str_val(style, "name");
            let doc_short = str_val(style, "doc_short");
            let doc_full = str_val(style, "doc_full");
            let since = style.get("since_version").and_then(|s| s.as_str());

            let since_str = match since {
                Some(v) => format!("Some({:?}.to_string())", v),
                None => "None".to_string(),
            };

            let related = generate_related_commands(style);
            let required = generate_style_params(style, "required_args");
            let optional = generate_style_params(style, "optional_args");

            code.push_str(&format!(
                "            StyleDef {{\n\
                                name: {:?}.to_string(),\n\
                                category: {},\n\
                                since_version: {},\n\
                                doc_short: {:?}.to_string(),\n\
                                doc_full: {:?}.to_string(),\n\
                                required_args: vec![{}],\n\
                                optional_args: vec![{}],\n\
                                related_commands: vec![{}],\n\
                            }},\n",
                name, category, since_str, doc_short, doc_full, required, optional, related
            ));
        }
    }

    code.push_str("        ],\n");
}

// ── Helper functions ──────────────────────────────────────────────

fn str_val(table: &toml::Value, key: &str) -> String {
    table
        .get(key)
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string()
}

fn map_command_category(cat: &str) -> &'static str {
    match cat {
        "Setup" => "CommandCategory::Setup",
        "Simulation" => "CommandCategory::Simulation",
        "Output" => "CommandCategory::Output",
        "Control" => "CommandCategory::Control",
        "Input" => "CommandCategory::Input",
        _ => {
            eprintln!("cargo:warning=Unknown command category: {}", cat);
            "CommandCategory::Setup"
        }
    }
}

fn generate_parameters(cmd: &toml::Value) -> String {
    let params = match cmd.get("parameters").and_then(|p| p.as_array()) {
        Some(p) => p,
        None => return String::new(),
    };

    let mut items = Vec::new();
    for param in params {
        let name = str_val(param, "name");
        let param_type = str_val(param, "param_type");
        let required = param
            .get("required")
            .and_then(|r| r.as_bool())
            .unwrap_or(false);
        let doc = str_val(param, "doc");
        let default = match param.get("default_value").and_then(|v| v.as_str()) {
            Some(v) => format!("Some({:?}.to_string())", v),
            None => "None".to_string(),
        };

        let param_type_enum = parse_param_type(&param_type);

        items.push(format!(
            "Parameter {{ \
             name: {:?}.to_string(), \
             param_type: {}, \
             required: {}, \
             default_value: {}, \
             doc: {:?}.to_string() \
             }}",
            name, param_type_enum, required, default, doc
        ));
    }

    items.join(", ")
}

fn generate_style_params(style: &toml::Value, key: &str) -> String {
    let params = match style.get(key).and_then(|p| p.as_array()) {
        Some(p) => p,
        None => return String::new(),
    };

    let mut items = Vec::new();
    for param in params {
        let name = str_val(param, "name");
        let param_type = str_val(param, "param_type");
        let required = param
            .get("required")
            .and_then(|r| r.as_bool())
            .unwrap_or(false);
        let doc = str_val(param, "doc");

        let param_type_enum = parse_param_type(&param_type);

        items.push(format!(
            "Parameter {{ \
             name: {:?}.to_string(), \
             param_type: {}, \
             required: {}, \
             default_value: None, \
             doc: {:?}.to_string() \
             }}",
            name, param_type_enum, required, doc
        ));
    }

    items.join(", ")
}

fn generate_related_commands(style: &toml::Value) -> String {
    let cmds = match style.get("related_commands").and_then(|c| c.as_array()) {
        Some(c) => c,
        None => return String::new(),
    };

    let items: Vec<String> = cmds
        .iter()
        .filter_map(|c| c.as_str())
        .map(|s| format!("{:?}.to_string()", s))
        .collect();

    items.join(", ")
}

/// Parse a TOML parameter type string into a Rust `ParameterType` enum expression.
fn parse_param_type(s: &str) -> String {
    let s = s.trim();

    // Repeat(Inner)
    if s.starts_with("Repeat(") && s.ends_with(')') {
        let inner = &s[7..s.len() - 1].trim();
        let inner_type = parse_param_type(inner);
        return format!("ParameterType::Repeat(Box::new({}))", inner_type);
    }

    // Enum([...])
    if s.starts_with("Enum(") && s.ends_with(')') {
        let inner = &s[5..s.len() - 1].trim();
        let items: Vec<String> = inner
            .trim_start_matches('[')
            .trim_end_matches(']')
            .split(',')
            .map(|item| item.trim().trim_matches('\'').trim_matches('"'))
            .filter(|i| !i.is_empty())
            .map(|i| format!("{:?}.to_string()", i))
            .collect();
        return format!("ParameterType::Enum(vec![{}])", items.join(", "));
    }

    // Keyword('...') or Keyword("...")
    if s.starts_with("Keyword(") && s.ends_with(')') {
        let inner = s[8..s.len() - 1]
            .trim()
            .trim_matches('\'')
            .trim_matches('"');
        return format!("ParameterType::Keyword({:?}.to_string())", inner);
    }

    // Simple types
    match s {
        "Style" => "ParameterType::Style".to_string(),
        "GroupId" => "ParameterType::GroupId".to_string(),
        "FixId" => "ParameterType::FixId".to_string(),
        "ComputeId" => "ParameterType::ComputeId".to_string(),
        "Variable" => "ParameterType::Variable".to_string(),
        "VariableName" => "ParameterType::VariableName".to_string(),
        "FileName" => "ParameterType::FileName".to_string(),
        "Label" => "ParameterType::Label".to_string(),
        "Integer" => "ParameterType::Integer".to_string(),
        "Float" => "ParameterType::Float".to_string(),
        "Boolean" => "ParameterType::Boolean".to_string(),
        "String" => "ParameterType::String".to_string(),
        "Expression" => "ParameterType::Expression".to_string(),
        other => {
            eprintln!(
                "cargo:warning=Unknown parameter type: '{}', falling back to ParameterType::String",
                other
            );
            "ParameterType::String".to_string()
        }
    }
}
